### ISSUE TITLE
[PATCH] Fix spelling errors in manpage

### ISSUE THREAD

**Issue by carnil** [Abigail/Regexp--Common#8]
Hi,

In Debian we are currently applying the following patch to
Regexp-Common.
We thought you might be interested in it too.

    Description: Fix spelling errors in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2016-05-28
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libregexp-common-perl.git/plain/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by Abigail** [comment]
On Fri, May 27, 2016 at 08:54:46PM -0700, carnil wrote:
> 
> Hi,
> 
> In Debian we are currently applying the following patch to
> Regexp-Common.
> We thought you might be interested in it too.
> 
>     Description: Fix spelling errors in manpage
>     Origin: vendor
>     Author: Salvatore Bonaccorso <carnil@debian.org>
>     Last-Update: 2016-05-28
>     
> 
> The patch is tracked in our Git repository at
> https://anonscm.debian.org/cgit/pkg-perl/packages/libregexp-common-perl.git/plain/debian/patches/spelling-error-in-manpage.patch
> 
> Thanks for considering,
>   Salvatore Bonaccorso,
>   Debian Perl Group



Thanks. This has been fixed in version 2016052803.


Regards,


Abigail

**Comment by carnil** [comment]
Hi Abigail

Thanks! I noticed that only the typo in delimited.pm was applied, but not hte one to lib/Regexp/Common/SEN.pm.

Thanks for the quick reply!

Salvatore

**Comment by Abigail** [comment]
On Sat, May 28, 2016 at 04:49:14AM -0700, carnil wrote:
> Hi Abigail
> 
> Thanks! I noticed that only the typo in delimited.pm was applied, but not hte one to lib/Regexp/Common/SEN.pm.


My bad. I missed that patch.

This should be fixed in version 2016052804.



Regards,


Abigail
